require("./base/sound-test");
require("./base/read-unread-test");
require("./base/pon-video-test");
require("./base/pon-sprite-test");
require("./base/pon-renderer-test");
require("./base/macro-test");
require("./base/script-parser-test");
require("./base/script-test");
require("./ponkan-test");
